In [20]:
data <- read.csv("dataset/Social_Network_Ads.csv")

In [21]:
data

    User.ID  Gender Age EstimatedSalary Purchased
1   15624510 Male   19   19000          0
2   15810944 Male   35   20000          0
3   15668575 Female 26   43000          0
4   15603246 Female 27   57000          0
5   15804002 Male   19   76000          0
6   15728773 Male   27   58000          0
7   15598044 Female 27   84000          0
8   15694829 Female 32  150000          1
9   15600575 Male   25   33000          0
10  15727311 Female 35   65000          0
11  15570769 Female 26   80000          0
12  15606274 Female 26   52000          0
13  15746139 Male   20   86000          0
14  15704987 Male   32   18000          0
15  15628972 Male   18   82000          0
16  15697686 Male   29   80000          0
17  15733883 Male   47   25000          1
18  15617482 Male   45   26000          1
19  15704583 Male   46   28000          1
20  15621083 Female 48   29000          1
21  15649487 Male   45   22000          1
22  15736760 Female 47   49000          1
23  15714658 Male   48   41000          1
24  15599081 Female 45   22000          1
25  15705113 Male   46   23000          1
26  15631159 Male   47   20000          1
27  15792818 Male   49   28000          1
28  15633531 Female 47   30000          1
29  15744529 Male   29   43000          0
30  15669656 Male   31   18000          0
... ...      ...    ... ...             ...
371 15611430 Female 60   46000          1
372 15774744 Male   60   83000          1
373 15629885 Female 39   73000          0
374 15708791 Male   59  130000          1
375 15793890 Female 37   80000          0
376 15646091 Female 46   32000          1
377 15596984 Female 46   74000          0
378 15800215 Female 42   53000          0
379 15577806 Male   41   87000          1
380 15749381 Female 58   23000          1
381 15683758 Male   42   64000          0
382 15670615 Male   48   33000          1
383 15715622 Female 44  139000          1
384 15707634 Male   49   28000          1
385 15806901 Female 57   33000          1
386 15775335 Male   56   60000          1
387 15724150 Female 49   39000          1
388 15627220 Male   39   71000          0
389 15672330 Male   47   34000          1
390 15668521 Female 48   35000          1
391 15807837 Male   48   33000          1
392 15592570 Male   47   23000          1
393 15748589 Female 45   45000          1
394 15635893 Male   60   42000          1
395 15757632 Female 39   59000          0
396 15691863 Female 46   41000          1
397 15706071 Male   51   23000          1
398 15654296 Female 50   20000          1
399 15755018 Male   36   33000          0
400 15594041 Female 49   36000          1

In [22]:
data <- data[,c(3:5)]

In [24]:
data

    Age EstimatedSalary Purchased
1   19   19000          0
2   35   20000          0
3   26   43000          0
4   27   57000          0
5   19   76000          0
6   27   58000          0
7   27   84000          0
8   32  150000          1
9   25   33000          0
10  35   65000          0
11  26   80000          0
12  26   52000          0
13  20   86000          0
14  32   18000          0
15  18   82000          0
16  29   80000          0
17  47   25000          1
18  45   26000          1
19  46   28000          1
20  48   29000          1
21  45   22000          1
22  47   49000          1
23  48   41000          1
24  45   22000          1
25  46   23000          1
26  47   20000          1
27  49   28000          1
28  47   30000          1
29  29   43000          0
30  31   18000          0
... ... ...             ...
371 60   46000          1
372 60   83000          1
373 39   73000          0
374 59  130000          1
375 37   80000          0
376 46   32000          1
377 46   74000          0
378 42   53000          0
379 41   87000          1
380 58   23000          1
381 42   64000          0
382 48   33000          1
383 44  139000          1
384 49   28000          1
385 57   33000          1
386 56   60000          1
387 49   39000          1
388 39   71000          0
389 47   34000          1
390 48   35000          1
391 48   33000          1
392 47   23000          1
393 45   45000          1
394 60   42000          1
395 39   59000          0
396 46   41000          1
397 51   23000          1
398 50   20000          1
399 36   33000          0
400 49   36000          1

In [25]:
str(data)

'data.frame':	400 obs. of  3 variables:
 $ Age            : int  19 35 26 27 19 27 27 32 25 35 ...
 $ EstimatedSalary: int  19000 20000 43000 57000 76000 58000 84000 150000 33000 65000 ...
 $ Purchased      : int  0 0 0 0 0 0 0 1 0 0 ...

In [27]:
#Encoding target feature as factor
data$Purchased <- as.factor(data$Purchased)
str(data)

'data.frame':	400 obs. of  3 variables:
 $ Age            : int  19 35 26 27 19 27 27 32 25 35 ...
 $ EstimatedSalary: int  19000 20000 43000 57000 76000 58000 84000 150000 33000 65000 ...
 $ Purchased      : Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 2 1 1 ...

In [31]:
library(caTools)
set.seed(1234)

In [33]:
split <- sample.split(Y = data$Purchased, SplitRatio = 3/4)
summary(split)

   Mode   FALSE    TRUE
logical     100     300

In [35]:
train  <- subset(data, split == T)
train

    Age EstimatedSalary Purchased
1   19   19000          0
2   35   20000          0
3   26   43000          0
4   27   57000          0
5   19   76000          0
6   27   58000          0
7   27   84000          0
8   32  150000          1
9   25   33000          0
10  35   65000          0
11  26   80000          0
12  26   52000          0
15  18   82000          0
17  47   25000          1
19  46   28000          1
22  47   49000          1
23  48   41000          1
24  45   22000          1
25  46   23000          1
26  47   20000          1
27  49   28000          1
28  47   30000          1
29  29   43000          0
30  31   18000          0
31  31   74000          0
32  27  137000          1
33  21   16000          0
34  28   44000          0
35  27   90000          0
37  33   28000          0
... ... ...             ...
359 40   71000          1
360 42   54000          0
365 42  104000          1
366 59   29000          1
367 58   47000          1
368 46   88000          1
369 38   71000          0
370 54   26000          1
371 60   46000          1
372 60   83000          1
375 37   80000          0
376 46   32000          1
377 46   74000          0
379 41   87000          1
380 58   23000          1
381 42   64000          0
382 48   33000          1
383 44  139000          1
385 57   33000          1
386 56   60000          1
387 49   39000          1
388 39   71000          0
390 48   35000          1
391 48   33000          1
392 47   23000          1
393 45   45000          1
394 60   42000          1
395 39   59000          0
396 46   41000          1
398 50   20000          1

In [56]:
test  <- subset(data, split == F)
test

    Age EstimatedSalary Purchased
13  20   86000          0
14  32   18000          0
16  29   80000          0
18  45   26000          1
20  48   29000          1
21  45   22000          1
36  35   27000          0
39  26   72000          0
48  27   54000          0
49  30  135000          1
53  29   83000          0
56  24   55000          0
57  23   48000          0
60  32  117000          0
62  25   87000          0
69  22   63000          0
70  31   68000          0
79  28   87000          0
86  31  118000          1
92  30  116000          0
94  29   28000          0
98  28  123000          1
113 38   61000          0
122 37   72000          0
123 40   75000          0
126 39   61000          0
128 26   32000          0
130 26   84000          0
132 33   31000          0
133 30   87000          0
... ... ...             ...
297 42   73000          1
300 46  117000          1
301 58   38000          1
302 48   74000          1
306 42   54000          0
311 42   70000          0
315 39   79000          0
320 36   60000          0
327 41   72000          0
329 36  118000          1
332 48  119000          1
334 40   65000          0
336 36   54000          0
337 58  144000          1
339 38   55000          0
352 37   75000          0
355 36   99000          1
357 54   70000          1
361 43  129000          1
362 53   34000          1
363 47   50000          1
364 42   79000          0
373 39   73000          0
374 59  130000          1
378 42   53000          0
384 49   28000          1
389 47   34000          1
397 51   23000          1
399 36   33000          0
400 49   36000          1

In [37]:
#Future Scaling
train[-3] = scale(train[-3])
train

    Age         EstimatedSalary Purchased
1   -1.7658065  -1.4953545      0
2   -0.2490078  -1.4658040      0
3   -1.1022071  -0.7861422      0
4   -1.0074072  -0.3724350      0
5   -1.7658065   0.1890248      0
6   -1.0074072  -0.3428845      0
7   -1.0074072   0.4254289      0
8   -0.5334076   2.3757628      1
9   -1.1970070  -1.0816473      0
10  -0.2490078  -0.1360309      0
11  -1.1022071   0.3072268      0
12  -1.1022071  -0.5201875      0
15  -1.8606064   0.3663279      0
17   0.8885913  -1.3180514      1
19   0.7937913  -1.2293999      1
22   0.8885913  -0.6088391      1
23   0.9833912  -0.8452432      1
24   0.6989914  -1.4067030      1
25   0.7937913  -1.3771525      1
26   0.8885913  -1.4658040      1
27   1.0781911  -1.2293999      1
28   0.8885913  -1.1702989      1
29  -0.8178073  -0.7861422      0
30  -0.6282075  -1.5249050      0
31  -0.6282075   0.1299238      0
32  -1.0074072   1.9916061      1
33  -1.5762067  -1.5840061      0
34  -0.9126072  -0.7565917      0
35  -1.0074072   0.6027320      0
37  -0.4386076  -1.2293999      0
... ...         ...             ...
359  0.22499181  0.04127222     1
360  0.41459165 -0.46108652     0
365  0.41459165  1.01643918     1
366  2.02619031 -1.19984937     1
367  1.93139039 -0.66794012     1
368  0.79379134  0.54363096     1
369  0.03539197  0.04127222     0
370  1.55219071 -1.28850091     1
371  2.12099023 -0.69749063     1
372  2.12099023  0.39587839     1
375 -0.05940795  0.30722684     0
376  0.79379134 -1.11119783     1
377  0.79379134  0.12992376     0
379  0.31979173  0.51408044     1
380  1.93139039 -1.37715246     1
381  0.41459165 -0.16558138     0
382  0.98339118 -1.08164732     1
383  0.60419150  2.05070717     1
385  1.83659047 -1.08164732     1
386  1.74179055 -0.28378344     1
387  1.07819110 -0.90434423     1
388  0.13019189  0.04127222     0
390  0.98339118 -1.02254629     1
391  0.98339118 -1.08164732     1
392  0.88859126 -1.37715246     1
393  0.69899142 -0.72704115     1
394  2.12099023 -0.81569269     1
395  0.13019189 -0.31333395     0
396  0.79379134 -0.84524320     1
398  1.17299102 -1.46580400     1

In [38]:
test[-3] = scale(test[-3])
test

    Age         EstimatedSalary Purchased
13  -1.71643000  0.45224629     0
14  -0.55537250 -1.48921507     0
16  -0.84563688  0.28094088     0
18   0.70243979 -1.26080785     1
20   0.99270416 -1.17515514     1
21   0.70243979 -1.37501146     1
36  -0.26510813 -1.23225695     0
39  -1.13590125  0.05253366     0
48  -1.03914646 -0.46138258     0
49  -0.74888209  1.85124051     1
53  -0.84563688  0.36659359     0
56  -1.32941083 -0.43283168     0
57  -1.42616563 -0.63268800     0
60  -0.55537250  1.33732427     0
62  -1.23265604  0.48079720     0
69  -1.52292042 -0.20442446     0
70  -0.65212729 -0.06166995     0
79  -0.94239167  0.48079720     0
86  -0.65212729  1.36587517     1
92  -0.74888209  1.30877336     0
94  -0.84563688 -1.20370604     0
98  -0.94239167  1.50862968     1
113  0.02515625 -0.26152627     0
122 -0.07159855  0.05253366     0
123  0.21866583  0.13818637     0
126  0.12191104 -0.26152627     0
128 -1.13590125 -1.08950243     0
130 -1.13590125  0.39514449     0
132 -0.45861771 -1.11805334     0
133 -0.74888209  0.48079720     0
... ...         ...             ...
297  0.41217541  0.081084563    1
300  0.79919458  1.337324267    1
301  1.96025207 -0.918197020    1
302  0.99270416  0.109635465    1
306  0.41217541 -0.461382582    0
311  0.41217541 -0.004568144    0
315  0.12191104  0.252389977    0
320 -0.16835334 -0.290077168    0
327  0.31542062  0.052533660    0
329 -0.16835334  1.365875169    1
332  0.99270416  1.394426072    1
334  0.21866583 -0.147322656    0
336 -0.16835334 -0.461382582    0
337  1.96025207  2.108198631    1
339  0.02515625 -0.432831680    0
352 -0.07159855  0.138186367    0
355 -0.16835334  0.823408024    1
357  1.57323291 -0.004568144    1
361  0.50893020  1.679935096    1
362  1.47647812 -1.032400630    1
363  0.89594937 -0.575586192    1
364  0.41217541  0.252389977    0
373  0.12191104  0.081084563    0
374  2.05700687  1.708485998    1
378  0.41217541 -0.489933485    0
384  1.08945895 -1.203706044    1
389  0.89594937 -1.032400630    1
397  1.28296853 -1.346460556    1
399 -0.16835334 -1.060951532    0
400  1.08945895 -0.975298825    1

In [40]:
#fitting logistic regression to the training set
?glm

In [43]:
classifier <- glm(formula = Purchased ~ .,
   family = binomial,
   data = train)

summary(classifier)

Call:
glm(formula = Purchased ~ ., family = binomial, data = train)

Deviance Residuals:
    Min       1Q   Median       3Q      Max
-2.8589  -0.5688  -0.1505   0.4231   2.3407

Coefficients:
                Estimate Std. Error z value Pr(>|z|)
(Intercept)      -1.1622     0.1964  -5.917 3.27e-09 ***
Age               2.3640     0.2993   7.898 2.84e-15 ***
EstimatedSalary   1.1165     0.2018   5.534 3.13e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 390.89  on 299  degrees of freedom
Residual deviance: 210.85  on 297  degrees of freedom
AIC: 216.85

Number of Fisher Scoring iterations: 6

In [47]:
# prediction of test

predict(object = classifier,
       type = "response",
       newdata = test[-3])

         13          14          16          18          20          21
0.008881495 0.015706884 0.054806020 0.287131477 0.468157197 0.261754884
         36          39          48          49          53          56
0.040514169 0.022122454 0.015768258 0.296172229 0.059976211 0.008258948
         57          60          62          69          70          79
0.005272128 0.272507615 0.028213015 0.006755654 0.058819104 0.054517520
         86          92          94          98         113         122
0.235270550 0.186749967 0.010930278 0.153738187 0.198654418 0.218778648
        123         126         128         130         132         133
0.379661532 0.237578962 0.006281173 0.032100411 0.029463737 0.083499658
        138         142         145         148         156         158
0.147020079 0.003184992 0.030554042 0.154889840 0.011405548 0.047111606
        160         167         172         173         174         175
0.399358387 0.005242930 0.357039023 0.089283146 0.052978783 0.123577689
        180         181         186         188         190         192
0.020703963 0.003781146 0.055387337 0.040082329 0.009888509 0.001051747
        193         198         205         209         210         213
0.017514382 0.001817005 0.988512183 0.838189415 0.308286836 0.942830123
        220         225         226         232         235         259
0.997582261 0.107860554 0.132564313 0.145334234 0.557503136 0.986124363
        260         267         272         274         276         280
0.919664463 0.379661532 0.979899379 0.566723514 0.966608448 0.634843637
        282         286         288         289         297         300
0.110966598 0.353573680 0.966010413 0.466363925 0.475697397 0.902052079
        301         302         306         311         315         320
0.920314051 0.787002429 0.331155734 0.451919023 0.356129969 0.131923624
        327         329         332         334         336         337
0.411470097 0.491212740 0.939428372 0.307941294 0.111518585 0.997057805
        339         352         355         357         361         362
0.169948614 0.235562303 0.345059376 0.927694344 0.871757488 0.764133719
        363         364         373         374         378         384
0.577656448 0.523477435 0.313573135 0.996345346 0.324133492 0.517319364
        389         397         399         400
0.450937822 0.590823384 0.060383655 0.580378268

In [52]:
prob_pred <- predict(object = classifier,
       type = "response",
       newdata = test[-3])

In [55]:
y_pred <- ifelse(prob_pred > 0.5, 1, 0)
y_pred

 13  14  16  18  20  21  36  39  48  49  53  56  57  60  62  69  70  79  86  92
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 94  98 113 122 123 126 128 130 132 133 138 142 145 148 156 158 160 167 172 173
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
174 175 180 181 186 188 190 192 193 198 205 209 210 213 220 225 226 232 235 259
  0   0   0   0   0   0   0   0   0   0   1   1   0   1   1   0   0   0   1   1
260 267 272 274 276 280 282 286 288 289 297 300 301 302 306 311 315 320 327 329
  1   0   1   1   1   1   0   0   1   0   0   1   1   1   0   0   0   0   0   0
332 334 336 337 339 352 355 357 361 362 363 364 373 374 378 384 389 397 399 400
  1   0   0   1   0   0   0   1   1   1   1   1   0   1   0   1   0   1   0   1

In [57]:
#making confusion matrix
table(test[,3],y_pred)
#(TP+TN)/all4

   y_pred
     0  1
  0 61  3
  1 13 23